spring:
  application:
    name: TaskManager

  datasource:
    url: jdbc:postgresql://taskmanager-v2.c7mo8iiugj1n.ap-south-1.rds.amazonaws.com:5432/taskmanagerv2?sslmode=require
    username: taskmanager
    password: taskmanager
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
      default_schema: taskmanager_schema
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8040/realms/master
server:
  port: 8080
